#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright 2026 Yakov Shkolnikov and contributors
"""Regenerate `docs/dev/persona_audit_tracker.md` + backing CSVs.

The tracker is the user-facing dashboard for:
  1. findings (open / fixed / wontfix-security-NO)
  2. parity (SKIFF vs Portainer / Docker Desktop / Lens / Dockge /
     Yacht / LazyDocker)
  3. GUI-elements seen in competitors
  4. testing (per-test-type count + coverage + last-run)
  5. open-work (fixme / todo / deferred / security-justified)

This stub scaffolds the file structure so `make tracker` exits 0.
Richer regeneration (git-log walks, cov.json ingestion, CSV merges)
lands in the competitor-matrix commit.
"""

from __future__ import annotations

import datetime as _dt
import json
from pathlib import Path


TRACKER_PATH = Path("docs/dev/persona_audit_tracker.md")
ARTIFACT_ROOT = Path("tests/e2e-artifacts/persona-audit")


def _count_findings() -> dict[str, int]:
    counts = {"open": 0, "fixed": 0, "wontfix": 0, "total": 0}
    if not ARTIFACT_ROOT.exists():
        return counts
    for finding_dir in ARTIFACT_ROOT.glob("pass-*/findings"):
        for fj in finding_dir.glob("*.json"):
            try:
                d = json.loads(fj.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            counts["total"] += 1
            counts[d.get("status", "open")] = counts.get(d.get("status", "open"), 0) + 1
    return counts


def main() -> int:
    TRACKER_PATH.parent.mkdir(parents=True, exist_ok=True)
    today = _dt.date.today().isoformat()
    counts = _count_findings()

    content = f"""# Persona audit tracker — refreshed {today}

> Regenerated by `scripts/regenerate_tracker.py` (run `make tracker`).
> Do not hand-edit — edit the source data (CSVs, `tests/journeys/_history.py`,
> the competitor matrix) and rerun.

## 1. Findings

- total (all passes): **{counts['total']}**
- fixed: **{counts.get('fixed', 0)}**
- open: **{counts.get('open', 0)}**
- wontfix (security_NO): **{counts.get('wontfix', 0)}**

Per-finding table in `docs/dev/findings_tracker.csv` (generated).

## 2. Parity matrix

Source: `docs/dev/competitor_matrix.csv`. Seeded from Portainer /
Docker Desktop / Lens / Dockge / Yacht / LazyDocker documentation.
Freshness: `last_verified` per row; 90-day gate enforced by
`tests/test_docs_sync.py::test_competitor_matrix_freshness`.

## 3. GUI-elements catalogue

Source: `docs/dev/competitor_gui_elements.csv`. One row per competitor
UI element with a SKIFF-analogue column.

## 4. Testing coverage

Per-test-type coverage rolled up from `coverage.json` and test-file
globs. See `docs/dev/testing_tracker.csv`.

## 5. Open-work

Source: `docs/dev/open_work_tracker.csv`. Every `fixme` / `todo` /
`deferred` / `wontfix(security_NO)` — exactly one row per thing.
"""

    TRACKER_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {TRACKER_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
